language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip setuptools
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest -v
  - pipenv run pyflakes .

#deploy:
#  provider: pypi
#  user: "MolopsDeploy"
#  password:
#    secure: "tX5VvpXIj7Afm9slPgCeSwelTxRnWPGfQcglTw92PoHlYeVbgiesEaH2uxIVS3cDeHWTHY4JsT/P2Juu6kZzga+Cb8thUND4JRYeUd1vizJblbeb5hgBRlQ8W/7x6k3j+Eh0I62HW7VDIiyM4uEBhigai4eJyuCK73pFmRmNfxw="
#  on:
#    tags: true
#    python: "3.6"
