language: python
dist: xenial

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install --upgrade 'pip<=18.0'  # see https://github.com/pypa/pipenv/issues/2924
  - pip install --upgrade setuptools
  - pip install pipenv
  - pipenv sync --dev
 
script:
  - make test

deploy:
 provider: pypi
 user: "MolopsDeploy"
 password:
   secure: "tX5VvpXIj7Afm9slPgCeSwelTxRnWPGfQcglTw92PoHlYeVbgiesEaH2uxIVS3cDeHWTHY4JsT/P2Juu6kZzga+Cb8thUND4JRYeUd1vizJblbeb5hgBRlQ8W/7x6k3j+Eh0I62HW7VDIiyM4uEBhigai4eJyuCK73pFmRmNfxw="
 on:
   tags: true
   python: "3.6"
